### ISSUE TITLE
Error: Cannot find module './chartPoints_formatter'

### ISSUE THREAD

**Issue by tanguybernard** [mpinardi/cucumber-performance-js#2]
Hello, I have a project with node v10.15.3
I have in my package.json _"cucumber-perf": "^1.0.3"_
And I found this error when I execute _./node_modules/.bin/cucumber-perf_

```
Error: Cannot find module './chartPoints_formatter'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> ({project_directory}/node_modules/cucumber-perf/lib/formatter/builder.js:18:53)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> ({project_directory}/node_modules/cucumber-perf/lib/cli/index.js:20:39)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> ({project_directory}/node_modules/cucumber-perf/lib/cli/run.js:8:32)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

Locally, I fixed the problem inside _node_modules/cucumber-perf/lib/formatter/builder.js_ by replacing:
`var _chartPoints_formatter = _interopRequireDefault(require("./chartPoints_formatter"));`
to
`var _chartPoints_formatter = _interopRequireDefault(require("./chartpoints_formatter"));`

If someone can help me to have a real fix ?

**Comment by mpinardi-bao** [comment]
You win a gold star. You are the first person to post a bug on this project.

I will look into putting out a bug fix patch. I am unsure however why i don't see this issue locally.

**Comment by tanguybernard** [comment]
It fixed the problem, thank you :+1:
